// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVK13NDQ9I87J5NErlaHQO1ABLDdUp6No',
    appId: '1:555367526667:web:825889247b255ce1e7f20e',
    messagingSenderId: '555367526667',
    projectId: 'rail-route-1999-92d40',
    authDomain: 'rail-route-1999-92d40.firebaseapp.com',
    storageBucket: 'rail-route-1999-92d40.firebasestorage.app',
    measurementId: 'G-9GZTJ7FP7H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6_nAVcfPKgNFr4Excoq3BrobxFlTmQgs',
    appId: '1:555367526667:android:39220a123c9347f8e7f20e',
    messagingSenderId: '555367526667',
    projectId: 'rail-route-1999-92d40',
    storageBucket: 'rail-route-1999-92d40.firebasestorage.app',
  );
}
